services:
  - type: web
    name: user-management
    env: node
    region: Singapore (Southeast Asia)
    buildCommand: "pnpm install"
    startCommand: "pnpm start"
    plan: free
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: AuthDB
          property: connectionString
      - key: PORT
        value: "5000"
